=== xjrga/potatosql/schema/config.xsd
<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="configuration">
        <!-- ************************************************************************************************ -->
        <xsd:annotation>
            <xsd:documentation>
                Configuration Document Schema For Potatosql Software
                Potatosql: Learning Software For Database Design
                Author: Jorge Rolando Garcia de Alba
                Version: 01
            </xsd:documentation>
        </xsd:annotation>
        <!-- ************************************************************************************************ -->
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="code_list" type="code_list" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
        <!-- ************************************************************************************************ -->
        <!-- unique table key -->
        <xsd:unique name="unique_code">
            <xsd:selector xpath="code_list/code"/>
            <xsd:field xpath="path"/>
        </xsd:unique>
    </xsd:element>
    <!-- ************************************************************************************************ -->
    <!-- table key list -->
    <xsd:complexType name="code_list">
        <xsd:sequence>
            <xsd:element name="code" type="code" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <!-- ************************************************************************************************ -->
    <!-- code -->
    <xsd:complexType name="code">
        <xsd:sequence>
            <xsd:element name="dialect" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="category" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="action" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="path" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="order" type="xsd:nonNegativeInteger" minOccurs="1" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <!-- ************************************************************************************************ -->
</xsd:schema>

=== xjrga/potatosql/template/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../schema/config.xsd'>
    <code_list>
        <code>
            <dialect>dot</dialect>
            <category>diagram</category>
            <action>erd</action>
            <name>dot, diagram, erd</name>
            <path>template/dot/diagram/erd.ftl</path>
            <order>1</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>admin</category>
            <action>jdbc</action>
            <name>hsqldb jdbc</name>
            <path>template/hsqldb/admin/jdbc.ftl</path>
            <order>2</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>function</category>
            <action>count</action>
            <name>hsqldb, function, count</name>
            <path>template/hsqldb/function/count.ftl</path>
            <order>3</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>function</category>
            <action>select</action>
            <name>hsqldb, function, select</name>
            <path>template/hsqldb/function/table_select.ftl</path>
            <order>4</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>function</category>
            <action>select all</action>
            <name>hsqldb, function, select all</name>
            <path>template/hsqldb/function/table_select_all.ftl</path>
            <order>5</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>function</category>
            <action>timestamp</action>
            <name>hsqldb, function, timestamp</name>
            <path>template/hsqldb/function/timestamp.ftl</path>
            <order>6</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>procedure</category>
            <action>delete</action>
            <name>hsqldb, procedure, delete</name>
            <path>template/hsqldb/procedure/delete.ftl</path>
            <order>7</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>procedure</category>
            <action>delete all</action>
            <name>hsqldb, procedure, delete all</name>
            <path>template/hsqldb/procedure/delete_all.ftl</path>
            <order>8</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>procedure</category>
            <action>insert</action>
            <name>hsqldb, procedure, insert</name>
            <path>template/hsqldb/procedure/insert.ftl</path>
            <order>9</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>procedure</category>
            <action>merge</action>
            <name>hsqldb, procedure, merge</name>
            <path>template/hsqldb/procedure/merge.ftl</path>
            <order>10</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>procedure</category>
            <action>select</action>
            <name>hsqldb, procedure, select</name>
            <path>template/hsqldb/procedure/select.ftl</path>
            <order>11</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>procedure</category>
            <action>select all</action>
            <name>hsqldb, procedure, select all</name>
            <path>template/hsqldb/procedure/select_all.ftl</path>
            <order>12</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>procedure</category>
            <action>update</action>
            <name>hsqldb, procedure, update</name>
            <path>template/hsqldb/procedure/update.ftl</path>
            <order>13</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>savepoint</category>
            <action>create</action>
            <name>hsqldb, savepoint, create</name>
            <path>template/hsqldb/savepoint/savepoint.ftl</path>
            <order>14</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>savepoint</category>
            <action>release</action>
            <name>hsqldb, savepoint, release</name>
            <path>template/hsqldb/savepoint/savepoint_release.ftl</path>
            <order>15</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>savepoint</category>
            <action>rollback</action>
            <name>hsqldb, savepoint, rollback</name>
            <path>template/hsqldb/savepoint/savepoint_rollback.ftl</path>
            <order>16</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>schema</category>
            <action>create</action>
            <name>hsqldb, schema, create</name>
            <path>template/hsqldb/schema/schema.ftl</path>
            <order>17</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>schema</category>
            <action>drop</action>
            <name>hsqldb, schema, drop</name>
            <path>template/hsqldb/schema/schema_drop.ftl</path>
            <order>18</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>schema</category>
            <action>set</action>
            <name>hsqldb, schema, set</name>
            <path>template/hsqldb/schema/schema_set.ftl</path>
            <order>19</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>sequence</category>
            <action>alter</action>
            <name>hsqldb, sequence, alter</name>
            <path>template/hsqldb/sequence/sequence_alter.ftl</path>
            <order>20</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>sequence</category>
            <action>create</action>
            <name>hsqldb, sequence, create</name>
            <path>template/hsqldb/sequence/sequence.ftl</path>
            <order>21</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>sequence</category>
            <action>value</action>
            <name>hsqldb, sequence, value</name>
            <path>template/hsqldb/sequence/sequence_value.ftl</path>
            <order>22</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>count</action>
            <name>hsqldb, statement, count</name>
            <path>template/hsqldb/statement/count.ftl</path>
            <order>23</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>delete</action>
            <name>hsqldb, statement, delete</name>
            <path>template/hsqldb/statement/delete.ftl</path>
            <order>24</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>delete all</action>
            <name>hsqldb, statement, delete all</name>
            <path>template/hsqldb/statement/delete_all.ftl</path>
            <order>25</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>insert</action>
            <name>hsqldb, statement, insert</name>
            <path>template/hsqldb/statement/insert.ftl</path>
            <order>26</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>insert using select</action>
            <name>hsqldb, statement, insert using select</name>
            <path>template/hsqldb/statement/insert_using_select.ftl</path>
            <order>27</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>merge</action>
            <name>hsqldb, statement, merge</name>
            <path>template/hsqldb/statement/merge.ftl</path>
            <order>28</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>select</action>
            <name>hsqldb, statement, select</name>
            <path>template/hsqldb/statement/select.ftl</path>
            <order>29</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>select all</action>
            <name>hsqldb, statement, select all</name>
            <path>template/hsqldb/statement/select_all.ftl</path>
            <order>30</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>statement</category>
            <action>update</action>
            <name>hsqldb, statement, update</name>
            <path>template/hsqldb/statement/update.ftl</path>
            <order>31</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>table</category>
            <action>audit</action>
            <name>hsqldb, table, audit</name>
            <path>template/hsqldb/table/audit.ftl</path>
            <order>32</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>table</category>
            <action>relationship</action>
            <name>hsqldb, table, relationship</name>
            <path>template/hsqldb/table/relationship.ftl</path>
            <order>33</order>
        </code>
        <code>
            <dialect>hsqldb</dialect>
            <category>table</category>
            <action>table</action>
            <name>hsqldb, table, table</name>
